# Generated by Django 4.2.7 on 2023-11-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='Age',
            new_name='Acquisition_Date',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='Email',
            new_name='Book_Name',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='First_Name',
            new_name='Return_Date',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='Last_Name',
            new_name='Serial_No',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='Mobile',
            new_name='Writer_Name',
        ),
    ]
