# Generated by Django 4.2.7 on 2023-11-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_age_library_acquisition_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='Age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='Mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='Acquisition_Date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='Book_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='Return_Date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='Serial_No',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='Writer_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
