# Generated by Django 4.2.7 on 2023-11-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_students_myimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='myImage',
            new_name='Image',
        ),
    ]
