# Generated by Django 4.2.7 on 2023-11-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_myimage_students_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Image',
            new_name='myImage',
        ),
    ]
