# Generated by Django 4.2.7 on 2023-11-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_image_students_myimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='myImage',
        ),
    ]
