# Generated by Django 4.2.7 on 2023-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_authority_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
    ]
