# Generated by Django 4.2.7 on 2023-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_library_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='Marks',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='Marks',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='Marks',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Marks',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='Marks',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
