# Generated by Django 4.2.7 on 2023-12-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_rename_marks_library_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='Marks',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='Marks',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='Marks',
            new_name='ID',
        ),
    ]
